theme: flyde
# min-version: 0.55
baseURL: https://adamweld.com/crosscast
languageCode: en-us
title: Crosscast

params:
  description: give me all the forecasts!
  themeColor: theme-base-08
  googleAnalytics: G-0Z2CX34J1S
  showBuiltWith: false
  postNavigation: false
  mainSections: sites

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - Name: Zones
    #   URL: /zones/
    #   weight: 000
    # - Name: All
    #   URL: /sites/
    #   weight: 100
    # - Name: Flying
    #   URL: /sites/flying
    #   weight: 200
    # - Name: Skiing
    #   URL: /sites/skiing
    #   weight: 300
    - Name: About
      URL: /about/
      weight: 400
  

  

