theme: flyde
baseURL: https://adamweld.com/crosscast
languageCode: en-us
title: CrossCast

params:
  description: all the forecasts
  themeColor: "theme-base-08"
  # googleAnalytics: Your tracking code
  showBuiltWith: false
  toc: hugo

Menus:
  main:
    - Name: All
      URL: /sites/
    - Name: Flying
      URL: /sites/flying
    - Name: Skiing
      URL: /sites/skiing
    - Name: About
      URL: /about/
  

  

